### ISSUE TITLE
部分貌似只有声音无画面

### ISSUE THREAD

**Issue by insoxin** [hw431/github-actions-youtube-dl#8]
https://m.youtube.com/watch?v=-0ukbc19gwk

**Comment by hw431** [comment]
建议你换一个播放器试试，我这里打开你 Release 中视频一点问题都没有
Actions 的运行日志我也看了，没有问题

![](https://ae03.alicdn.com/kf/U8111a32367ff4440834d6992f7b4fde6I.jpg)
